export default {
  className: "mobile-drawer-container",
  headerClassName: "text-center",
  bodyClassName: "hideScrollbar",
  position: "bottom",
  width: "80%",
  height: "80%",
  id: "u:2389sfdf0",
  actions: [
    {
      type: "button",
      label: "确定",
      block: true,
      primary: true,
      style: {
        height: "44px",
      },
      close: false,
      onEvent: {
        click: {
          actions: [
            {
              actionType: "validate",
              componentId: "u:2d6b457c3914",
              stopPropagation: "${event.data.validateResult.error}",
            },
            {
              actionType: "confirm",
              componentId: "u:2389sfdf0",
            },
            {
              actionType: "closeDialog",
            },
          ],
        },
      },
    },
  ],
  title: "意见反馈",
  body: {
    type: "form",
    id: "u:2d6b457c3914",
    title: "",
    dsType: "api",
    debug: false,
    wrapWithPanel: false,
    mode: "horizontal",
    className: "mobile-form-right",
    api: {
      method: "post",
      url: "/platform/api/feedBack/save",
      messages: {
        success: "提交成功",
      },
    },
    body: [
      {
        type: "radios",
        label: "反馈类型",
        name: "type",
        joinValues: false,
        selectFirst: true,
        mode: "inline",
        inputClassName: "is-inline",
        source: {
          method: "get",
          url:
            "/platform/api/common/options?className=com.maiyue.dianda.platform.feedback.domian.FeedBackType",
        },
        id: "u:9929cb8eb369",
        required: true,
      },
      {
        type: "select",
        label: "问题类型",
        name: "problemCategoryId",
        visibleOn: "${type.value === 'ProblemFeedback'}",
        valueField: "id",
        labelField: "name",
        source: {
          method: "get",
          url: "/platform/api/problemCategory/query",
        },
        id: "u:d6bf089ccb2d",
        multiple: false,
        required: true,
      },
      {
        type: "textarea",
        label: "问题描述",
        placeholder: "请详细描述问题具体发生的步骤和现象，帮助问题更快处理",
        visibleOn: "${type.value === 'ProblemFeedback'}",
        name: "content",
        id: "u:607831903ce6",
        minRows: 3,
        maxRows: 20,
        required: true,
      },
      {
        type: "textarea",
        label: "您的建议",
        visibleOn: "${type.value !== 'ProblemFeedback'}",
        placeholder: "请输入",
        name: "content",
        id: "u:607831903ce6",
        minRows: 3,
        maxRows: 20,
        required: true,
      },
      {
        type: "input-image",
        label: "图片上传",
        name: "icon",
        receiver: "/fs/api/attachment/upload",
        autoUpload: true,
        proxy: true,
        urlPrefix: "${CONTEXT_ROOT}",
        uploadType: "fileReceptor",
        imageClassName: "r w-full",
        id: "u:33076974b4d0",
        accept: ".jpeg, .jpg, .png",
        multiple: true,
        maxLength: 9,
        joinValues: false,
        hideUploadButton: false,
      },
      {
        type: "control",
        label: "",
        body: [
          {
            type: "tpl",
            className: "text-gray-400",
            tpl: "建议上传辅助问题描述，支持：JPEG、JPG、PNG，最多可上传9张",
            style: {
              "font-size": "var(--fonts-size-7)",
            },
          },
        ],
      },
    ],
    actions: [],
    resetAfterSubmit: true,
  },
};
